add_newline = true

[username]
disabled = false
show_always = true

[git_status]
conflicted = 'âš”ï¸'
ahead = 'ğŸ ğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
untracked = 'â“â“ <200d>'
modified = 'ğŸ“'
renamed = ''
deleted = 'ğŸ—‘ '
staged = '[++\($count\)](green)'

[battery]
disabled = true
