model= "gpt-5-codex"

# https://github.com/openai/codex/blob/main/docs/config.md#approval_policy
approval_policy = "on-request"
model_reasoning_effort = "medium"

web_search_request = true


[mcp_servers.figma-dev-mode-mcp-server]
startup_timeout_ms = 5_000
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.deepwiki]
startup_timeout_ms = 5_000
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.context7]
startup_timeout_ms = 5_000
url = "https://mcp.context7.com/mcp"

[mcp_servers.chrome-devtools]
command = "aqua"
args = [
  "exec",
  "bunx",
  "chrome-devtools-mcp@latest"
]

[mcp_servers.lsmcp-tsgo]
command="aqua"
args=[
  "exec",
  "bunx",
  "-y",
  "@mizchi/lsmcp@latest",
  "-p",
  "tsgo",
]

[mcp_servers.devenv]
command="devenv"
args=[
  "mcp"
]

