name: Nix Build

on:
  push:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'nix/**'
      - '.github/workflows/nix-build.yaml'
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    name: Build macOS (nix-darwin)
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/actions/setup-nix
        with:
          flakehub-token: ${{ secrets.FLAKEHUB_SECRET_TOKEN }}

      - name: Build macOS configuration
        run: |
          nix build .#darwinConfigurations.ryoppippi.system \
            --print-build-logs \
            --show-trace
