name: 'CI: Neovim plugins'

on:
  push:
    paths:
      - 'nvim/**'
      - 'flake.nix'
      - '.github/workflows/nix-neovim.yaml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  neovim-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check Neovim configuration
        run: nix run .#nvim-restore
        env:
          DOTFILES_DIR: ${{ github.workspace }}
