name: Nix Neovim

on:
  push:
    paths:
      - 'nvim/**'
      - 'flake.nix'
      - '.github/workflows/nix-neovim.yaml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  neovim-check:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check Neovim configuration
        run: nix run .#nvim-check
        env:
          DOTFILES_DIR: ${{ github.workspace }}
