name: Renovate config linter

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - .github/renovate.json5
  pull_request:

jobs:
  renovate-validate:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
