name: Renovate config linter

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - .github/renovate.json5
  pull_request:

jobs:
  renovate-validate:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@ca480cb7ec89a9e1cd8c214ad33bda1617184027 # v2.0.0
